### ISSUE TITLE
Test example with `form` and `render_submit`

### ISSUE THREAD

**Issue by RodolfoSilva** [nkezhaya/live_phone#120]
Are there any example tests that show how to make `live_phone` work with a standard live view test, using the `form` and `render_submit` functions?

When I try to test I get an error:

```elixir
 ** (ArgumentError) value for hidden "contact[phone]" must be one of [""], got: "+55 (11) 98123-1234"
 code: |> render_submit()
```

**Comment by nkezhaya** [comment]
@RodolfoSilva do you have a repo or something where this is reproduced? Happy to look into it.

**Comment by RodolfoSilva** [comment]
@nkezhaya,

Here is the repository with the example:

https://github.com/RodolfoSilva/live-phone-example

And the test file:

https://github.com/RodolfoSilva/live-phone-example/commit/26d148e765822568a7b2be8d18de6319c7c4fd07#diff-f2b7cce06da833a08aa65a8772167d7be05d0b86f20328694d1f5701c590b1c5

**Comment by nkezhaya** [comment]
@RodolfoSilva Thanks for the repo! This is because `form/3` doesn't allow passing hidden inputs. If you pass it into `render_submit` or `render_change`, it should work. For example:

```elixir
      assert index_live
             |> form("#contact-form", contact: %{name: "name"})
             |> render_submit(%{contact: %{phone: "+1123123123"}})
```

**Comment by RodolfoSilva** [comment]
This works. Thanks @nkezhaya 😛
