### ISSUE TITLE
Issue with live_phone Component Not Opening Country List in Umbrella Application

### ISSUE THREAD

**Issue by LameckMeshack** [nkezhaya/live_phone#148]
I noticed that the path to the CSS in an umbrella application was a bit different. The following worked for me:

```css
@import "../../../../deps/live_phone/assets/live_phone";
```

After fixing the CSS path, I observed that the `live_phone` component does not open the country list when clicked. However, in the demo app, it worked as expected. I'm not sure if this issue is specific to umbrella applications or if it's an issue on my side.

Any guidance would be appreciated. Thank you!

**Comment by nkezhaya** [comment]
I'd check the the hooks in your JS file. See here: https://github.com/nkezhaya/live_phone/blob/master/example/assets/js/app.js

**Comment by LameckMeshack** [comment]
Following the documentation I configured it this way

```
import * as Hooks from "./hooks";
import Alpine from "alpinejs";
import live_select from "live_select";
import LivePhone from "live_phone";

window.Alpine = Alpine;
Alpine.start();

let csrfToken = document
  .querySelector("meta[name='csrf-token']")
  .getAttribute("content");
let liveSocket = new LiveSocket("/live", Socket, {
  longPollFallbackMs: 2500,
  params: { _csrf_token: csrfToken },
  hooks: { ...Hooks, ...live_select, LivePhone },
  dom: {
    onBeforeElUpdated(from, to) {
      if (from._x_dataStack) {
        window.Alpine.clone(from, to);
      }
    },
  },
});
```
